apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spotify-collab
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
spec:
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: spotify-collab-tls
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: spotify-collab
            port:
              number: 80
